Работа с пользователями и вещами.
Anna-Vashchenkova/java-shareit pull request #1
Opened 2024-02-01 21:11 UTC by Anna-Vashchenkova

2024-02-02 22:23 UTC, avlin87 requested changes
Привет, Анна,
Работа выглядит хорошо, автоматические проверки проходит, заданию соответствует.
Добавь, пожалуйста, логирование. Сейчас я его увидел только в ErrorHanler классе.
И сделай, пожалуйста, переменные классов приватными даже в классах моделях.

2024-02-02 22:23 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/config/ErrorResponse.java
> +    String error;
`можно лучше`
Полня класса лучше делать приватными.

2024-02-02 22:23 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/config/ErrorResponse.java
> +}
`можно лучше`
Добавь, пожалуйста, так же изменения в класс Booking в пакете booking, при проверке ожидаются атрибуты:
- id — уникальный идентификатор бронирования;
- start — дата начала бронирования;
- end — дата конца бронирования;
- item — вещь, которую пользователь бронирует;
- booker — пользователь, который осуществляет бронирование;
- status — статус бронирования. Может принимать одно из следующих значений: WAITING — новое бронирование, ожидает одобрения, APPROVED — бронирование подтверждено владельцем, REJECTED — бронирование отклонено владельцем, CANCELED— бронирование отменено создателем.

это указано в конце задания:
`Если задание показалось вам недостаточно подробным, вы можете обратиться к этому файлу`

**`Для этого спринта класс не обязательный - по этому комментарий помечем "можно лучше"`**

2024-02-03 09:33 UTC, Anna-Vashchenkova commented on src/main/java/ru/practicum/shareit/config/ErrorResponse.java
> +}
Добавила.

2024-02-03 09:33 UTC, Anna-Vashchenkova commented on src/main/java/ru/practicum/shareit/config/ErrorResponse.java
> +    String error;
Сделала

2024-02-04 04:25 UTC, avlin87 approved these changes
Работу принимаю.

2024-02-19 23:36 UTC, merged