Добавление функции бронирования и комментариев
Anna-Vashchenkova/java-shareit pull request #4
Opened 2024-02-19 23:46 UTC by Anna-Vashchenkova

2024-02-20 07:25 UTC, avlin87 requested changes
Привет, Ань,
Хорошая работа, комментарии, смотри, пожалуйста, ниже.

2024-02-20 07:25 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>  /**
`можно лучше`
Комментарии лучше оставлять только информативные. 
В данном случае у нас просто подпись спринта в котором работаем над классом.
Лучше удалить.

2024-02-20 07:25 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingOutcomeDto.java
>  /**
`можно лучше`
Комментарии лучше оставлять только информативные. 
В данном случае у нас просто подпись спринта в котором работаем над классом.
Лучше удалить.

2024-02-20 07:25 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/item/CommentServiceImpl.java
> +    private  final CommentRepository repository;
В этой и следующей строке между private и final два пробела. 
Сократи, пожалуйста, количество пробелов до одного.

2024-02-20 07:25 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        /*if ((user.getEmail() == null) || (user.getEmail().isEmpty()) || (!user.getEmail().contains("@"))) {
Удали, пожалуйста, закомментированный код.

2024-02-20 07:25 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
>   * TODO Sprint add-item-requests.
Удали, пожалуйста, комментарий.

2024-02-20 07:25 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +        /*Booking lastBooking = bookings.stream()
Удали, пожалуйста, закомментированный код.

2024-02-20 07:25 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +        /*Booking nextBooking = bookings.stream()
Удали, пожалуйста, закомментированный код.

2024-02-20 11:09 UTC, Anna-Vashchenkova commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>  /**
Всё исправила!)

2024-02-21 01:43 UTC, avlin87 approved these changes
Хорошо, работу принимаю.

2024-02-25 19:18 UTC, merged