Add item requests
Anna-Vashchenkova/java-shareit pull request #5
Opened 2024-03-03 20:38 UTC by Anna-Vashchenkova

2024-03-06 09:04 UTC, avlin87 requested changes
Привет, Ань,
Работа выглядит хорошо, смотри, пожалуйста, комментарии ниже.

2024-03-06 09:04 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>          log.info("Получен запрос на получение " +
`можно лучше`
В запросе добавили параметров. 
Может быть лучше и в логировании это отобразить?

2024-03-06 09:04 UTC, avlin87 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    BookingService bookingService;
Добавь, пожалуйста, модификатор доступа.

2024-03-07 10:43 UTC, Anna-Vashchenkova commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>          log.info("Получен запрос на получение " +
+

2024-03-07 10:54 UTC, Anna-Vashchenkova commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    BookingService bookingService;
+

2024-03-07 15:10 UTC, avlin87 approved these changes
Все хорошо, работу принимаю.

2024-03-11 09:10 UTC, merged