Add docker
Anna-Vashchenkova/java-shareit pull request #6
Opened 2024-03-14 21:32 UTC by Anna-Vashchenkova

2024-03-16 06:57 UTC, avlin87 requested changes
Привет, Ань,
Работа выглядит хорошо, задание выполнено, очень круто, что применяешь webflux.
Смотри, пожалуйста, комментарии ниже.

2024-03-16 06:57 UTC, avlin87 commented on server/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
`Отлично`
Отлично, что dependency валидации убраны из `server`.

2024-03-16 06:57 UTC, avlin87 commented on gateway/src/main/java/ru/practicum/shareit/gateway/booking/controller/BookingController.java
> +                .uri("/bookings")
`Можно лучше`
Вынеси, пожалуйста, `/bookings` в переменную класса, например:
`private static final String API_PREFIX = "/bookings";`
чтобы не прописывать его в каждом месте.

2024-03-16 06:57 UTC, avlin87 commented on gateway/src/main/java/ru/practicum/shareit/gateway/booking/controller/BookingController.java
> +    private final WebClient webClient;
`вопрос:`
А вам не предоставили текст класса `BookingClient` ?
Он присутствует в чужих работах у всех.

2024-03-16 06:57 UTC, avlin87 commented on gateway/src/main/java/ru/practicum/shareit/gateway/booking/controller/BookingController.java
> +    public BookingOutcomeDto saveNewBooking(@RequestHeader("X-Sharer-User-Id") Long userId,
WebFlux использует асинхронный и неблокирующий веб-стек.
По этому при использовании `response.block()`  происходит блокировка и преимущества WebFlux теряются.
Вместо `BookingOutcomeDto` попробуй, пожалуйста, возвращать `Mono<BookingOutcomeDto>`.
Мне кажется тесты должны принять такой вариант.

```
return webClient.post()
                .uri("/bookings")
                .header("X-Sharer-User-Id", String.valueOf(userId))
                .contentType(MediaType.APPLICATION_JSON)
                .bodyValue(dto)
                .retrieve()
                .onStatus(httpStatus -> httpStatus.equals(HttpStatus.BAD_REQUEST),
                        clientResponse -> Mono.error(new ValidationException("Невалидные данные запроса")))
                .onStatus(httpStatus -> httpStatus.equals(HttpStatus.NOT_FOUND),
                        clientResponse -> Mono.error(new DataNotFoundException("Бронирование не найдено")))
                .bodyToMono(BookingOutcomeDto.class);
```

2024-03-16 21:27 UTC, Anna-Vashchenkova commented on server/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Спасибо!

2024-03-16 21:36 UTC, Anna-Vashchenkova commented on gateway/src/main/java/ru/practicum/shareit/gateway/booking/controller/BookingController.java
> +                .uri("/bookings")
+

2024-03-16 21:48 UTC, Anna-Vashchenkova commented on gateway/src/main/java/ru/practicum/shareit/gateway/booking/controller/BookingController.java
> +    public BookingOutcomeDto saveNewBooking(@RequestHeader("X-Sharer-User-Id") Long userId,
+
Это надо запомнить для собесов)))
"WebFlux использует асинхронный и неблокирующий веб-стек."

2024-03-16 22:26 UTC, Anna-Vashchenkova commented on gateway/src/main/java/ru/practicum/shareit/gateway/booking/controller/BookingController.java
> +    private final WebClient webClient;
Предоставили. Я про RestTemplate начала читать, чтоб разобраться. И увидела
"Тем не менее, если мы разрабатываем новые приложения или переносим старые, рекомендуется использовать WebClient . В дальнейшем RestTemplate будет считаться устаревшим в будущих версиях."
https://www.baeldung.com/rest-template
Стало интересно попробовать этот WebClient .

2024-03-17 13:25 UTC, avlin87 requested changes
Добавил пару советов, попробуй, пожалуйста, их применить.

2024-03-17 13:25 UTC, avlin87 commented on gateway/src/main/java/ru/practicum/shareit/gateway/booking/controller/BookingController.java
> +                .onStatus(httpStatus -> httpStatus.is4xxClientError(),
`можно лучше`
тут и в других подобных местах можно заменить лямбду на ссылку на метод
`.onStatus(HttpStatus::is4xxClientError`

2024-03-17 13:25 UTC, avlin87 commented on gateway/src/main/java/ru/practicum/shareit/gateway/user/controller/UserController.java
> +    /*@DeleteMapping("/{userId}")
Закомментированный код всегда лучше удалять.

2024-03-17 13:25 UTC, avlin87 commented on gateway/src/main/java/ru/practicum/shareit/gateway/user/controller/UserController.java
> +                .uri(API_PREFIX + "/{userId}", userId)
`/{userId}` лучше так же вынести в константу.

2024-03-17 13:25 UTC, avlin87 commented on gateway/src/main/java/ru/practicum/shareit/gateway/user/controller/UserController.java
>      public void deleteUser(@PathVariable("userId") Long userId) {
Скорее всего у тебя и в другом классе не выполняется удаление сущности.
В реактивном стэке у нас должен быть потребитель, в противном случае операция не выполнится.
Из-за этого в реактивном стэке есть рекомендация не делать методы Void.
Но если нам все же нужно, то есть неблокирующие операции по вызову реквеста "потреблению" - `.subscribe();`

 ```
webClient.delete()
                .uri(API_PREFIX + "/{userId}", userId)
                .retrieve()
                .subscribe();
```

bodyToMono, мне кажется, нам не нужен, если мы не возвращаем ничего.

2024-03-17 13:25 UTC, avlin87 commented on gateway/src/main/java/ru/practicum/shareit/gateway/user/controller/UserController.java
>                  .retrieve()
Для того чтобы лучше понимать, что происходит:
1. можно добавить проверку статуса, в противном случае для webClient любой статус уже результат
```
...
.retrieve()
.onStatus(HttpStatus::is4xxClientError,
                    clientResponse -> Mono.error(new DataNotFoundException("User not found")))
.onStatus(HttpStatus::is5xxServerError,
                    clientResponse -> Mono.error(new ServerException("Server error occurred")))
...
```
2. можно добавить логирование результатов операции:
```
...
.doOnSuccess(success -> log.debug("...."))
.doOnError(error -> log.error("...")))
.subscribe();
```

2024-03-18 01:39 UTC, Anna-Vashchenkova commented on gateway/src/main/java/ru/practicum/shareit/gateway/user/controller/UserController.java
> +    /*@DeleteMapping("/{userId}")
Забыла

2024-03-18 01:40 UTC, Anna-Vashchenkova commented on gateway/src/main/java/ru/practicum/shareit/gateway/user/controller/UserController.java
> +                .uri(API_PREFIX + "/{userId}", userId)
Сделала

2024-03-18 01:42 UTC, Anna-Vashchenkova commented on gateway/src/main/java/ru/practicum/shareit/gateway/user/controller/UserController.java
>      public void deleteUser(@PathVariable("userId") Long userId) {
Спасибо, сделала, теперь точно работает Delete, локально запросами проверила. Только без bodyToMono метод subscribe нельзя было использовать. Локально

2024-03-18 04:34 UTC, avlin87 approved these changes
Работу принимаю.

2024-03-21 19:16 UTC, merged